config/routes.rb
Rails.application.routes.draw do
  get 'statuses/create'
  get 'statuses/destroy'
  get 'privatetasks/create'
  get 'privatetasks/destroy'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  get 'toppages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get "users/:id/fin_task" => "users#fin_task"
  get "users/:id/unfin_task" => "users#unfin_task"
  resources :users, only: [:index, :show, :new, :create]
  resources :privatetasks, onry: [:create, :destroy, :edit, :show]
  post "privatetasks/:id/progres" => "privatetasks#progres"
  post "privatetasks/:id/unprogres" => "privatetasks#unprogres"
  get "privatetasks/:id/edit" => "privatetasks#edit"
  get "privatetasks/:user_id/:category" => "privatetasks#category"
  post "privatetasks/:user_id/all_destroy" => "privatetasks#all_destroy"
  post "privatetasks/:id/create_category" => "privatetasks#create_category"
  resources :statuses, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/privatetask.rb
class Privatetask < ApplicationRecord
  belongs_to :user
  
  validates :task, presence: true, length: { maximum: 255 }
  
  validates :deadline, presence: true
  validates :progress, presence: false
  # validates :category, presence: true
  
  has_one :status
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :privatetask
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }

    has_secure_password
    
    has_many :privatetasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    
    private 
     def require_user_logged_in
         unless logged_in?
         redirect_to login_url
         end
     end
     
     def counts(user)
         @count_p_tasks = user.privatetasks.count
     end
end

app/controllers/privatetasks_controller.rb
class PrivatetasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @p_task = current_user.privatetasks.build(ptask_params)
    @p_task.category = params[:category]
    @p_task.progress = "2020-01-01 00:00:00"
      if @p_task.save
        flash[:success] = 'タスクを設定しました!'
        redirect_to root_url
      else
        # @Ptasks = current_user.privatetasks.order(id: :desc).page(params[:page])
        flash[:danger] = 'タスクの設定に失敗しました。'
        redirect_to root_url
      end
  end

  def destroy
    @p_task.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def all_destroy
    @user = User.find(params[:user_id])
    @user.privatetasks.destroy_all
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def edit
  end
  
  def show
    @task = Privatetask.find(params[:id])
    @user = User.find(@task.user_id)
  end
  
  def progres
    @task = Privatetask.find(params[:id])
    @task.progress = DateTime.now
    @task.save
    flash[:notice] = "お疲れ様でした"
    redirect_to("/privatetasks/#{params[:id]}")
  end
  
  def unprogres
    @task = Privatetask.find(params[:id])
    @task.progress = "2020-01-01 00:00:00"
    @task.save
    flash[:notice] = "ファイト！"
    redirect_to("/privatetasks/#{params[:id]}")
  end
  
  def edit
    @task = Privatetask.find(params[:id])
  end
  
  def create_category
    @task = Privatetask.find(params[:id])
    @task.category = params[:category]
    @task.task = params[:task]
    if @task.save
      flash[:notice] = "編集しました"
      redirect_to("/privatetasks/#{params[:id]}")
    end
  end
  
  def category
    @user = User.find(params[:user_id])
    @tasks = @user.privatetasks
    if params[:category] == "none_categories"
      @category = "カテゴリーなし"
      @same_categories = @tasks.where(category: nil)
    else
      @category = params[:category]
      @same_categories = @tasks.where(category: params[:category])
    end
  end
  
  private
  
  def ptask_params
    params.require(:privatetask).permit(:task, :deadline)
  end
  
  def correct_user
    @p_task = current_user.privatetasks.find_by(id: params[:id])
    unless @p_task
      redirect_to root_url
      flash[:danger] = '更新できません。'
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインできませんでした。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
   def login(email, password)
     @user = User.find_by(email: email)
     if @user && @user.authenticate(password)
       session[:user_id] = @user.id
       return true
     else
       return false
     end
   end
end

app/controllers/statuses_controller.rb
class StatussController < ApplicationController
  before_action :correct_user
  
  def new
    if logged_in?
      @status = current_user.privatetasks.statuses.build
      @Ptasks = current_user.privatetasks.all
    end
  end
  
  def create
    @p_task.status = DateTime.now
    redirect_to root_url
  end

  def destroy
  end
  
  private
  
  def correct_user
    @p_task = current_user.privatetasks.find_by(id: params[:id])
    unless @p_task
      redirect_to root_url
      flash[:danger] = '更新できません。'
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @Ptask = current_user.privatetasks.build
      @p_tasks = current_user.privatetasks.all
      @user = User.find(current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show ,:fin_task, :unfin_task]
  before_action :user_shows, only:[:show, :fin_task, :unfin_task]
  
  
  def index
    @users = User.all
  end

  def show
  end
  
  def fin_task
    @tasks = @p_tasks
    @p_tasks = @p_tasks.where("progress != '2019-12-31 15:00:00'").order(id: "DESC")
  end
  
  def unfin_task
    @tasks = @p_tasks
    @p_tasks = @p_tasks.where("progress = '2019-12-31 15:00:00'").order(id: "DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = '登録が完了しました。'
      redirect_to ("/users/#{@user.id}")
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_shows
      @user = User.find(params[:id])
      @p_tasks = @user.privatetasks.all.order(id: "DESC")
      counts(@user)
    if @current_user.privatetasks.count != 0
      @unfin_count = Privatetask.where(progress: "2019-12-31 15:00:00",user_id:@user.id).count
      @fin_count = @p_tasks.count - @unfin_count
      @fin_per =  @fin_count * 100 / @p_tasks.count
      @categories =[]
      @nowtime = DateTime.now
       if @nowtime.day == 31
         @d = 1
       else
         @d = @nowtime.day
       end
      @soon = @p_tasks.where(deadline: "#{@nowtime.year}-#{@nowtime.month}-#{@d} 15:00:00", progress: "2019-12-31 15:00:00")
      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/privatetasks_helper.rb
module PrivatetasksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
        
end

app/helpers/statuss_helper.rb
module StatussHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="md-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">EasyWork</a>
        <button class="navbar-toggler" tyoe="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class ="navbar-nav">
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to 'タスク作成', "/",class: 'nav-link'%></li>
                    <li class="nav-item"><%= link_to 'ログアウト', logout_path,class: 'nav-link', method: :delete %></li>
                <% else %>
                    <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
            <!--<ul class="dropdown-menu dropdown-menu-right">-->
            <!--    <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>-->
            <!--</ul>-->
        </div>
    </nav>
    
</header>

app/views/layouts/_tasks.html.erb
<ul class="list-unstyled">
    <% @p_tasks.each do | p_task | %>
       <% deadline_time = p_task.deadline %>
       <% create_time = p_task.created_at %>
            <li>
                <div class="media-body">
                    <p>期限：<%= "#{deadline_time.year}/#{deadline_time.month}/#{deadline_time.day}" %>
                    <span class="text-muted"> 設定日：<%= "#{create_time.year}/#{create_time.month}/#{create_time.day}" %></span></p>
                </div>
                <div>
                    <p><%= link_to p_task.task,"/privatetasks/#{p_task.id}", class: "text-dark" %></p>
                </div>
                <div>
                  <% if current_user == p_task.user %>
                    <%= render 'privatetasks/progress', p_task: p_task %>
                    <%= link_to "削除", p_task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-secondary btn-sm' %>
                 
                </div>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Easywork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/privatetasks/_fin_ptasks.html.erb
<ul class="list-unstyled">
    <% p_tasks.each do | p_task | %>
        <% if p_task.progress != "2020-01-01 00:00:00" %>
            <li>
                <div class="media-body">
                    <p>期限：<%= p_task.deadline %> <span class="text-muted"> 設定日：<%= p_task.created_at %></span></p>
                    <p><%= p_task.progress %></p>
                </div>
                <div>
                    <p><%= link_to(p_task.task,"/privatetasks/#{p_task.id}") %></p>
                </div>
                <div>
                  <% if current_user == p_task.user %>
                    <%= render 'privatetasks/progress', p_task: p_task %>
                    <%= link_to "削除", p_task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-secondary btn-sm' %>
                  <% end %>
                </div>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/privatetasks/_progress.html.erb
<% if p_task.progress != "2019-12-31 15:00:00" %>
    <%= link_to "完了済", "/privatetasks/#{p_task.id}/unprogres", method: "post", data: { confirm: "未完了に戻しますか？" },class: 'btn btn-primary btn-sm'%>
<% else %>
    <%= link_to "未完了", "/privatetasks/#{p_task.id}/progres", method: "post", class: 'btn btn-danger btn-sm'%>
<% end %>

app/views/privatetasks/category.html.erb
<h1>「<%= @category %>」一覧</h1>

<ul class="list-unstyled">
    <% if @same_categories.count == 0 %>
        <h2 class="w-100 text-center mt-5">このカテゴリーは空です。</h2>
    <% end %>
    <% @same_categories.each do | p_task | %>
        <% deadline_time = p_task.deadline %>
        <% create_time = p_task.created_at %>
        <li>
            <div class="media-body">
                <p>期限：<%= "#{deadline_time.year}/#{deadline_time.month}/#{deadline_time.day}" %>
                <span class="text-muted"> 設定日：<%= "#{create_time.year}/#{create_time.month}/#{create_time.day}" %></span></p>
            </div>
            <div>
                <p><%= link_to(p_task.task,"/privatetasks/#{p_task.id}") %></p>
            </div>
            <div>
              <% if current_user == p_task.user %>
                <%= render 'privatetasks/progress', p_task: p_task %>
                <%= link_to "削除", p_task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-secondary btn-sm' %>
              <% end %>
            </div>
        </li>
    <% end %>
    <%= link_to 'タスク一覧ページ' , "/users/#{@user.id}" %>
</ul>

app/views/privatetasks/edit.html.erb
<div class="text-center border rounded">
  <% deadline_time = @task.deadline %>
  <% create_time = @task.created_at %>
  <div class="media-body">
      <p><span class="text-muted"> 設定日：<%= "#{create_time.year}/#{create_time.month}/#{create_time.day}" %></span></p>
  </div>
  <div>
      <%= form_tag("/privatetasks/#{@task.id}/create_category") do %>
       <p><label>タスク内容</label>
       <input name="task" value="<%= @task.task %>"></p>
       <p class="mb-2"><label>カテゴリー</label>
       <input name="category" value="<%= @task.category %>"></p>
       <p class="mb-0"><label>期限設定</label></p>
       <input name="deadline_year" value="<%= deadline_time.year %>" class="text-center w-auto">年
       <input name="deadline_month" value="<%= deadline_time.month %>" class="text-center">月
       <input name="deadline_day" value="<%= deadline_time.day %>" class="text-center">日
       <p class="mt-4"><input type="submit" value="送信" class='btn btn-primary btn-block w-25 ml-auto mr-auto'></p>
       
      <% end %>
  </div>
  <div>
    <% if current_user == @task.user %>
      <%= render 'privatetasks/progress', p_task: @task %>
      <%= link_to "削除", @task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-secondary btn-sm' %>
    <% end %>
    <%  @user = User.find(@task.user_id) %>
      <p><%= link_to("ユーザー詳細ページ","/users/#{@user.id}") %></p>
  </div>
</div> 

app/views/privatetasks/show.html.erb
<div class="text-center border rounded">
  <% deadline_time = @task.deadline %>
  <% create_time = @task.created_at %>
  <div class="media-body">
      <p>期限：<%= "#{deadline_time.year}/#{deadline_time.month}/#{deadline_time.day}" %>
      <span class="text-muted"> 設定日：<%= "#{create_time.year}/#{create_time.month}/#{create_time.day}" %></span></p>
  </div>
  <div>
      <p><%= link_to @task.task,"/privatetasks/#{@task.id}", class: "text-dark" %></p>
  </div>
  <div>
    <% if current_user == @task.user %>
      <%= render 'privatetasks/progress', p_task: @task %>
      <%= link_to "削除", @task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-secondary btn-sm' %>
      <p><%= link_to("編集","/privatetasks/#{@task.id}/edit") %></p>
    <% end %>
      <p><%= link_to("タスク一覧ページ","/users/#{@user.id}") %></p>
  </div>
</div> 

app/views/statuses/_done_btn.html.erb
<% if p_task.status == nil %>
    <%= link_to "完了した", p_task, method: :create, class: 'btn btn-primary btn-sm' %>
<% else %>
    <%= link_to "Delete", p_task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
<% end %>

app/views/toppages/index.html.erb
   <% if logged_in? %>
        <h2 class="text-center">ようこそ <%= current_user.name %> さん</h2>
        
        <div class="row">
            <aside class="col-sm-4">
                <%= form_with(model: @Ptask, local: true) do|f| %>
                    <div class="form-group">
                        <label>タスク内容</label>
                        <%= f.text_area :task, class: 'form-control', rows: 5 %>
                        <label>カテゴリー</label>
                        <!--<%= f.text_field :category, class: 'form-control' %>-->
                        <input name="category" class="form-control">
                        <label>期限設定</label>
                        <%= f.text_field :deadline, class: 'form-control date-picker', :placeholder => "2020-12-31" %>
                        
                        
                    </div>
                    <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
                <% end %>
                    <%= link_to '詳細ページ' , "users/#{@user.id}" %>
            </aside>
            
            <div class="col-sm-6">
                <%= render 'layouts/tasks' %>
            </div>
        </div>
    <% else %>
    <div class="text-center">
        <h1 class="mt-5">手軽にタスク管理する</h1>
        <h1 class="mb-5">EasyWork</h1>
        <button type="button" class="btn btn-success w-25"><%= link_to '新規登録', signup_path, :style => "color: white;"  %></button>
        <button type="button" class="btn btn btn-info w-25"><%= link_to  'ログイン', login_path, :style => "color: white;"  %></button>
    </div>
    <% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/fin_task.html.erb
<div class="row text-center">
    <aside class="col-sm-3 mx-auto d-block">
    <img class="rounded img-fluid float-md-right" src="<%= gravatar_url(@user, { size: 100}) %>" alt="">
    </aside>
    
    <div class="col-sm-8 text-center text-md-left">
        <h3><%= @user.name %>さんのタスク一覧</h3>
        <p>未達成タスク：<%= @unfin_count %>件　タスク達成率：<%= @fin_per %>％</p>
        <% if @soon == nil || @soon.count == 0%>
            <p>直近の未達成タスクはありません。</p>
        <% else %>
            <p class="text-danger">直近の未達成タスクが<%= @soon.count %>件あります</p>
        <% end %>
    </div>
</div>

<div class="row">
    <aside class="col-sm-4 text-center">
        <h3>カテゴリー別</h3>
        <ul class="list-group">
            <% @tasks.each do |p_task| %>
                <% if p_task.category== nil || p_task.category=="" %>
                  <% @none_categories = p_task %>
                <% else %>
                  <% if @categories.include?("#{p_task.category}") %>
                  <% else %>
                    <% @categories.push(p_task.category) %>
                    <li class="list-group-item"><%= link_to p_task.category, "/privatetasks/#{@user.id}/#{p_task.category}", class: "text-dark" %></li>
                  <% end %>
                <% end %>
            <% end %>
            <li class="list-group-item"><%= link_to "カテゴリーなし","/privatetasks/#{@user.id}/none_categories", class: "text-dark" %></li>
        </ul>
        <%= link_to "タスクを全て消去", "/privatetasks/#{@user.id}/all_destroy", method: :post, data: { confirm: "全てのタスクを消去しますか?" }, class: 'btn btn-danger btn-sm mt-3 mb-5' %>
        <%= link_to 'タスクを新規作成', "/",class: 'btn btn-info btn-sm mt-3 mb-5' %>
    </aside>
    <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link">全てのタスク<span class="badge badge-secondary"><%= @count_p_tasks %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/fin_task"class="nav-link active">達成済タスク  <span class="badge badge-secondary"><%= @fin_count %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/unfin_task"class="nav-link">未達成タスク  <span class="badge badge-secondary"><%= @unfin_count %></span></a></li>
    </ul>
    
    <%= render 'layouts/tasks' %>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="row text-center">
    <aside class="col-sm-3 mx-auto d-block">
    <img class="rounded img-fluid float-md-right" src="<%= gravatar_url(@user, { size: 100}) %>" alt="">
    </aside>
    
    <div class="col-sm-8 text-center text-md-left">
        <h3><%= @user.name %>さんのタスク一覧</h3>
        <p>未達成タスク：<%= @unfin_count %>件　タスク達成率：<%= @fin_per %>％</p>
        <% if @soon == nil || @soon.count == 0%>
            <p>直近の未達成タスクはありません。</p>
        <% else %>
            <p class="text-danger">直近の未達成タスクが<%= @soon.count %>件あります</p>
        <% end %>
    </div>
</div>

<div class="row">
    <aside class="col-sm-4 text-center">
        <h3>カテゴリー別</h3>
        <ul class="list-group">
            <% @p_tasks.each do |p_task| %>
                <% if p_task.category== nil || p_task.category=="" %>
                  <% @none_categories = p_task %>
                <% else %>
                  <% if @categories.include?("#{p_task.category}") %>
                  <% else %>
                    <% @categories.push(p_task.category) %>
                    <li class="list-group-item"><%= link_to p_task.category, "/privatetasks/#{@user.id}/#{p_task.category}", class: "text-dark" %></li>
                  <% end %>
                <% end %>
            <% end %>
            <li class="list-group-item"><%= link_to "カテゴリーなし","/privatetasks/#{@user.id}/none_categories", class: "text-dark" %></li>
        </ul>
        <%= link_to "タスクを全て消去", "/privatetasks/#{@user.id}/all_destroy", method: :post, data: { confirm: "全てのタスクを消去しますか?" }, class: 'btn btn-danger btn-sm mt-3 mb-5' %>
        <%= link_to 'タスクを新規作成', "/",class: 'btn btn-info btn-sm mt-3 mb-5' %>
    </aside>
    <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">全てのタスク<span class="badge badge-secondary"><%= @count_p_tasks %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/fin_task"class="nav-link">達成済タスク  <span class="badge badge-secondary"><%= @fin_count %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/unfin_task"class="nav-link">未達成タスク  <span class="badge badge-secondary"><%= @unfin_count %></span></a></li>
    </ul>
    
      
    
    <%= render 'layouts/tasks' %>
    
  </div>
</div>

app/views/users/unfin_task.html.erb
<div class="row text-center">
    <aside class="col-sm-3 mx-auto d-block">
    <img class="rounded img-fluid float-md-right" src="<%= gravatar_url(@user, { size: 100}) %>" alt="">
    </aside>
    
    <div class="col-sm-8 text-center text-md-left">
        <h3><%= @user.name %>さんのタスク一覧</h3>
        <p>未達成タスク：<%= @unfin_count %>件　タスク達成率：<%= @fin_per %>％</p>
        <% if @soon == nil || @soon.count == 0%>
            <p>直近の未達成タスクがはありません。</p>
        <% else %>
            <p class="text-danger">直近の未達成タスクが<%= @soon.count %>件あります</p>
        <% end %>
        
    </div>
</div>

<div class="row">
    <aside class="col-sm-4 text-center">
        <h3>カテゴリー別</h3>
        <ul class="list-group">
            <% @tasks.each do |p_task| %>
                <% if p_task.category== nil || p_task.category=="" %>
                  <% @none_categories = p_task %>
                <% else %>
                  <% if @categories.include?("#{p_task.category}") %>
                  <% else %>
                    <% @categories.push(p_task.category) %>
                    <li class="list-group-item"><%= link_to p_task.category, "/privatetasks/#{@user.id}/#{p_task.category}", class: "text-dark" %></li>
                  <% end %>
                <% end %>
            <% end %>
            <li class="list-group-item"><%= link_to "カテゴリーなし","/privatetasks/#{@user.id}/none_categories", class: "text-dark" %></li>
        </ul>
        <%= link_to "タスクを全て消去", "/privatetasks/#{@user.id}/all_destroy", method: :post, data: { confirm: "全てのタスクを消去しますか?" }, class: 'btn btn-danger btn-sm mt-3 mb-5' %>
        <%= link_to 'タスクを新規作成', "/",class: 'btn btn-info btn-sm mt-3 mb-5' %>
    </aside>
    <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link">全てのタスク<span class="badge badge-secondary"><%= @count_p_tasks %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/fin_task"class="nav-link">達成済タスク  <span class="badge badge-secondary"><%= @fin_count %></span></a></li>
      <li class="nav-item"><a href="/users/<%= @user.id %>/unfin_task"class="nav-link active">未達成タスク  <span class="badge badge-secondary"><%= @unfin_count %></span></a></li>
    </ul>
    
    <%= render 'layouts/tasks' %>
    
  </div>
</div>